on:
  workflow_dispatch:
  
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Pull upstream changes
      id: sync
      uses: cognifloyd/Fork-Sync-With-Upstream-action@has-new-commits
      with:
        upstream_repository: panr/hugo-theme-hello-friend
        upstream_branch: master

    - name: Timestamp
      if: steps.sync.outputs.has-new-commits
      run: date